name: Default pull request checks

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  runs-on: ubuntu-latest
  default-checks:
    steps:
    - name: Run check for secrets
      run: echo "Checking for secrets"
