name: Default pull request checks

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  default-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Run check for secrets
      run: echo "Checking for secrets"
